# Stage 1: Build
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .

RUN npm run build -- --configuration=production --base-href=/

# Stage 2: Nginx
FROM nginx:alpine

# Ajusta "nombre-de-tu-proyecto" al valor real de tu angular.json
COPY --from=build /app/dist/Inventario-almacen/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
