FROM node:20-alpine

WORKDIR /app

# Angular CLI
RUN npm install -g @angular/cli

# Dependencias
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Código
COPY . .

EXPOSE 4200

CMD ["npm", "start"]
